"""
Task 1
 Go to your implementation of the Phonebook application from module 1 or any other comprehensive code, which you have
 done during the course, and annotate this code with type hints, using knowledge from this lesson.
 
Task 2
Use Mypy project (https://github.com/python/mypy) to perform static type check ing of your code. Play around a little
bit with Mypy, go through results and reports generated by running the mypy, perform refactoring based on the mentioned
results.
 
 --> Lesson_13/Task2
"""